# Generated by Django 3.2.5 on 2021-12-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explain', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_coment', models.CharField(max_length=200)),
                ('bad_coment', models.CharField(max_length=200)),
                ('explain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.explain')),
            ],
        ),
    ]
