# Generated by Django 3.2.5 on 2021-12-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
        migrations.DeleteModel(
            name='Explain',
        ),
    ]
