# Generated by Django 3.2.5 on 2021-12-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211218_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='words',
            field=models.TextField(default='', verbose_name='특징'),
        ),
    ]
