# Generated by Django 3.2.5 on 2021-12-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211218_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=256, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='product',
            name='words',
            field=models.TextField(default='', verbose_name='특징단어'),
        ),
    ]
