# Generated by Django 3.2.5 on 2021-12-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='register_date',
            new_name='create_time',
        ),
    ]
